adjusted front-end to access the upload endpoint. need to work on the…
joseph-w-valdez/marvelous pull request #25
Opened 2023-03-01 18:43 UTC by joseph-w-valdez

… backend functionality to both upload the file and add the url to that file to the user in the db

2023-03-01 19:25 UTC, RobertGardner requested changes
Remove the component embedding!

2023-03-01 19:25 UTC, RobertGardner commented on client/pages/Register.jsx
> +  const FileInput = ({ onChange }) => {
React docs warn you to _never_ embed one component's code inside another component. Pull this out to the top level. Pass any props it might need.

2023-03-01 19:25 UTC, RobertGardner commented on client/pages/Register.jsx
> +          axios.post(uploadUrl, formData);
Oh, you're still posting as FormData. That should be easy to deal with on the backend using the exercises uploadMiddleware.

2023-03-01 21:47 UTC, joseph-w-valdez commented
https://images-ext-1.discordapp.net/external/Dyc2gJW-qv3VdVqb3VpcEiZJJtOavHBZJruJ6q4bhsM/https/i.imgur.com/e7wdO9e.png?width=1074&height=577

2023-03-02 00:02 UTC, joseph-w-valdez commented
![image](https://user-images.githubusercontent.com/117682160/222295067-d914ba05-4a36-4e05-b0cd-b2d5fb3ceffd.png)

2023-03-02 00:09 UTC, RobertGardner approved these changes

2023-03-02 00:45 UTC, joseph-w-valdez commented
![image](https://user-images.githubusercontent.com/117682160/222301533-5c5677da-a2fa-45b7-83c0-b905b8949dea.png)

2023-03-02 01:01 UTC, RobertGardner approved these changes

2023-03-02 10:47 UTC, merged